#!/bin/bash -e

mkdir -p /srv/mail/domains
mkdir -p /srv/mail/filters
mkdir -p /srv/mail/trash

chown vmail:vmail /srv/mail
chown -Rh vmail:vmail /srv/mail/domains /srv/mail/filters /srv/mail/trash
chmod 700 /srv/mail /srv/mail/domains /srv/mail/filters /srv/mail/trash

exec /usr/sbin/dovecot -F -c /etc/dovecot/dovecot.conf 2>&1
