#!/bin/bash -e

# This scripts restarts amavisd-new after spamassassin rules got updated.
# This version of the script uses runit.

# Exit if amavis is not running.
sv status amavis > /dev/null || exit

sv restart amavis > /dev/null
