#!/bin/bash -e

# Restrict access to the file so that it can contain sensitive content.
chmod 640 /etc/amavis/conf.d/50-user
chown :amavis /etc/amavis/conf.d/50-user

# Logging goes to syslog (mail).

exec /usr/sbin/amavisd-new foreground 2>&1
