#!/bin/bash -e

mkdir -p /var/run/clamav
chown clamav:clamav /var/run/clamav

DATABASEDIR="/var/lib/clamav"

# Check for database existence (start will fail if it is missing).
for db in main daily; do
  if [ ! -e "$DATABASEDIR"/"$db".cvd ] && [ ! -d "$DATABASEDIR"/"$db".inc ] && [ ! -e "$DATABASEDIR"/"$db".cld ]; then
    echo "Clamav signatures missing in $DATABASEDIR, running freshclam..."
    chpst -u clamav:clamav /usr/bin/freshclam 2>&1
    # We exit to retry if now signatures are there.
    exit 0
  fi
done

exec chpst -u clamav:clamav /usr/sbin/clamd 2>&1
