#!/bin/bash -e

DATABASEDIR="/var/lib/clamav"

# Check for database existance (start will fail if it's missing).
for db in main daily; do
  if [ ! -e "$DATABASEDIR"/"$db".cvd ] && [ ! -d "$DATABASEDIR"/"$db".inc ] && [ ! -e "$DATABASEDIR"/"$db".cld ]; then
    echo "Clamav signatures missing in $DATABASEDIR"
    # Sleep a bit so that we do not retry immediately.
    sleep 30
    exit 1
  fi
done

exec chpst -u clamav:clamav /usr/sbin/clamd 2>&1
